version: '3'

services:
  demowallet-client-app:
    image: demowallet-client-app:1
    build:
      context: demowallet-client
      dockerfile: Dockerfile
    volumes:
      - /data/demowallet-client-app
    depends_on:
      - demowallet-server-app
    environment:
      - DEMOWALLET_CLIENT_USERS=${WALLET_USERS}
      - DEMOWALLET_CLIENT_CONCURRENT_THREADS_PER_USER=${CONCURRENT_THREADS_PER_USER}
      - DEMOWALLET_CLIENT_ROUNDS_PER_THREAD=${ROUNDS_PER_THREAD}
      - DEMOWALLET_CLIENT_PERFINFO=${SHOW_PERFINFO}
      - GRPC_CLIENT_LOCAL_ADDRESS=static://demowallet-server-app:9091
      - GRPC_CLIENT_LOCAL_NEGOTIATIONTYPE=PLAINTEXT
  demowallet-server-app:
    image: demowallet-server-app:1
    build:
      context: demowallet-server
      dockerfile: Dockerfile
    depends_on:
      - walletdb
    volumes:
      - /data/demowallet-server-app
    ports:
      - "9091:9091"
    environment:
      - GRPC_SERVER_PORT=9091
      - SPRING_DATASOURCE_URL=jdbc:mysql://walletdb:3306/walletdb?useSSL=false
      - SPRING_DATASOURCE_USERNAME=wallet
      - SPRING_DATASOURCE_PASSWORD=demo
  walletdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'walletdb'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'wallet'
      MYSQL_PASSWORD: 'demo'
    ports:
      - "3306:3306"
    volumes:
      - walletdb:/var/lib/mysql
volumes:
  walletdb: